import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "../..");
const sourcePath = path.join(repoRoot, "backend/data/bus_data.json");
const outputDir = path.join(repoRoot, "frontend/src/data");
const outputPath = path.join(outputDir, "staticBusRoutes.js");

function cleanText(value) {
  if (typeof value !== "string") return null;
  const cleaned = value.replace(/\s+/g, " ").trim();
  return cleaned || null;
}

function normalizeStop(stop) {
  return {
    order: Number(stop.order),
    name: cleanText(stop.name),
    nameBn: cleanText(stop.nameBn),
    raw: cleanText(stop.raw)
  };
}

function normalizeBus(bus) {
  return {
    name: cleanText(bus.name),
    nameBn: cleanText(bus.nameBn),
    slug: cleanText(bus.slug),
    seatingType: cleanText(bus.seatingType),
    operatingHours: {
      start: cleanText(bus.operatingHours?.start),
      end: cleanText(bus.operatingHours?.end)
    },
    stops: (Array.isArray(bus.stops) ? bus.stops : [])
      .map(normalizeStop)
      .filter((stop) => stop.name && Number.isInteger(stop.order))
  };
}

function main() {
  const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
  const routes = (Array.isArray(source.buses) ? source.buses : [])
    .map(normalizeBus)
    .filter((bus) => bus.name && bus.stops.length >= 2);

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(
    outputPath,
    `// Generated by frontend/scripts/generateStaticBusRoutes.js\n` +
      `// Source: backend/data/bus_data.json\n` +
      `const STATIC_BUS_ROUTES = ${JSON.stringify(routes)};\n\n` +
      `export { STATIC_BUS_ROUTES };\n`,
    "utf8"
  );

  console.log(`Generated ${routes.length} static bus routes at ${outputPath}`);
}

main();
